replicaCount: 5
image:
  repository: fischernz/passin
  pullPolicy: Always
  tag: c328f8a
  port: 3333
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 8
  targetMemoryUtilizationPercentage: 75
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
