apiVersion: apps/v1

kind: Deployment

metadata:
  name: passin-deployment
  labels:
    app: passin
    
spec:
  selector: 
    matchLabels:
      app: passin
  replicas: 5
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
      - name: passin
        image: fischernz/passin:2f9b1f7
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: url
          - name: API_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: nlw-env
                key: url
        ports:
        - containerPort: 3333
        resources:
          requests: 
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
