apiVersion: v1
kind: Secret

metadata:
  name: private-repo
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git
  url: git@github.com:FischerRobson/nlw-unite-devops.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----