name: CI

on: 
  push: 
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=${SHA}" >> $GITHUB_OUTPUT

    - name: Docker Build Image
      run: docker build -t fischernz/passin:${{ steps.generate_sha.outputs.sha }} -f passin-api/api/Dockerfile passin-api/api/

    - name: Log into DockerHub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Image
      run: |
        docker push fischernz/passin:${{ steps.generate_sha.outputs.sha }}
        docker tag fischernz/passin:${{ steps.generate_sha.outputs.sha }} fischernz/passin:latest
        docker push fischernz/passin:latest
